In [0]:
import pandas as pd
import numpy as np

데이터

In [0]:

#colab사용시 
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
pwd

'/content'

In [0]:
cd pandas

/content/drive/My Drive/Colab Notebooks/200406-13/pandas

In [0]:

ls

dataLearning/  day1/  day2/  day3/  Numpy/  pandas/  txt/

In [0]:
from pathlib import Path
import os

data_path ="./"

print(f"현재 디렉토리 위치: {os.getcwd()}")

현재 디렉토리 위치: /content/drive/My Drive/Colab Notebooks/200406-13/pandas

# 데이터 로딩, 저장

|pandas file 파싱 함수|설명|
|---|---|
|read_csv|파일, url, 파일과 유사한 객체로부터 구분된 데이터 읽어옴. 데이터 구분자는 쉼표(,)가 기본|
|read_excel|엑셀(xls, xlsx)에서 표 형식의 데이터를 읽어옴.|
|read_json|JSON 문자열에서 데이터를 읽어옴.|
|read_pickle|파이썬 피클 포맷으로 저장된 객체를 읽어옴..|

## csv

In [0]:
# 데이터 읽기 
stock = pd.read_csv(os.path.join(data_path, 'stock_2020_01.csv'), 
                    encoding = "euc-kr")

In [0]:
stock.head(3)

                    Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745

In [0]:
stock.to_csv(os.path.join(data_path,'stock_2020_01_tmp.csv'))

In [0]:
# 데이터 쓰기 
stock.to_csv(os.path.join(data_path,'stock_2020_01_tmp.csv'))

## json

In [0]:
movie_2019 = pd.read_json(os.path.join(data_path,'movie_2019.json'))

In [0]:
movie_2019.head(2)

   순위         영화명         개봉일  ...  대표국적  국적                 배급사
0   1        극한직업  2019-01-23  ...    한국  한국           씨제이이앤엠(주)
1   2  어벤져스: 엔드게임  2019-04-24  ...    미국  미국  월트디즈니컴퍼니코리아 유한책임회사

[2 rows x 11 columns]

In [0]:
movie_2019.to_json(os.path.join(data_path, 'movie_2019_tmp.json'))

# Data structure

## Series

### series 생성

In [0]:
obj1 = pd.Series([10, 20, 30, 40]) 
obj1

0    10
1    20
2    30
3    40
dtype: int64

In [0]:
# dtype
obj1 = pd.Series([10, 20, 30, 40], dtype = np.float32)
obj1

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float32

In [0]:
# index
obj2 = pd.Series(['a','b', 'c'], index = ['i1','i2','i3'])
obj2

i1    a
i2    b
i3    c
dtype: object

In [0]:
# dictionary
dic = {'서울특별시'	: '02',  '경기도'	: '031', '인천광역시'	: '032', '강원도'	: '033',
      '충청남도'	: '041', '대전광역시'	: '042', '충청북도'	: '043', '세종특별자치시'	: '044',
      '부산광역시'	: '051', '울산광역시'	: '052', '대구광역시'	: '053',  '경상북도'	: '054 ',
      '경상남도'	: '055', '전라남도'	: '061', '광주광역시'	: '062', '전라북도'	: '063',
      '제주특별자치도' : '064'}

In [0]:
obj3 = pd.Series(dic)
obj3

서울특별시        02
경기도         031
인천광역시       032
강원도         033
충청남도        041
대전광역시       042
충청북도        043
세종특별자치시     044
부산광역시       051
울산광역시       052
대구광역시       053
경상북도       054
경상남도        055
전라남도        061
광주광역시       062
전라북도        063
제주특별자치도     064
dtype: object

In [0]:
# numpy 
obj4 = pd.Series(np.arange(4), name='kk')
obj4

0    0
1    1
2    2
3    3
Name: kk, dtype: int64

### index, values

In [0]:
obj1

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float32

In [0]:
obj1.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
obj1.values

array([10., 20., 30., 40.], dtype=float32)

In [0]:
obj2

i1    a
i2    b
i3    c
dtype: object

In [0]:
obj2.index

Index(['i1', 'i2', 'i3'], dtype='object')

In [0]:
obj2.values

array(['a', 'b', 'c'], dtype=object)

In [0]:
obj3

서울특별시        02
경기도         031
인천광역시       032
강원도         033
충청남도        041
대전광역시       042
충청북도        043
세종특별자치시     044
부산광역시       051
울산광역시       052
대구광역시       053
경상북도       054
경상남도        055
전라남도        061
광주광역시       062
전라북도        063
제주특별자치도     064
dtype: object

In [0]:
obj3.index

Index(['서울특별시', '경기도', '인천광역시', '강원도', '충청남도', '대전광역시', '충청북도', '세종특별자치시',
       '부산광역시', '울산광역시', '대구광역시', '경상북도', '경상남도', '전라남도', '광주광역시', '전라북도',
       '제주특별자치도'],
      dtype='object')

In [0]:
obj3.values

array(['02', '031', '032', '033', '041', '042', '043', '044', '051',
       '052', '053', '054 ', '055', '061', '062', '063', '064'],
      dtype=object)

In [0]:
obj4

0    0
1    1
2    2
3    3
Name: kk, dtype: int64

In [0]:
obj4.index

RangeIndex(start=0, stop=4, step=1)

In [0]:
obj4.values

array([0, 1, 2, 3])

## Data *Frame*

### Data Frame *생성*

In [0]:
#dictionary
data = {'제목': ['극한직업', '어벤져스: 엔드게임', '알라딘', '기생충', '엑시트', '스파이더맨: 파 프롬 홈', '겨울왕국 2', '캡틴 마블', '조커', '봉오동 전투'],
        '감독': ['이병헌', '안소니 루소,조 루소', '가이 리치', '봉준호', '이상근', '존 왓츠', '크리스 벅,제니퍼 리', '애너 보든,라이언 플렉', '토드 필립스', '원신연,이영용'],
        '관객수': [16264944, 13934592, 12551956, 10084564, 9424431, 8020208, 7603956, 5801069, 5245841, 4777456]
}
frame1 = pd.DataFrame(data)

In [0]:
frame1.head(3)

           제목           감독       관객수
0        극한직업          이병헌  16264944
1  어벤져스: 엔드게임  안소니 루소,조 루소  13934592
2         알라딘        가이 리치  12551956

In [0]:
# numpy
frame2 = pd.DataFrame(np.arange(10).reshape(2,-1))
frame2

   0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

### index, columns, values

In [0]:
frame2.index

RangeIndex(start=0, stop=2, step=1)

In [0]:
frame2.columns

RangeIndex(start=0, stop=5, step=1)

In [0]:
frame2.values

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
stock.head(5)

                    Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3  2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4  2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270

In [0]:
stock.index

RangeIndex(start=0, stop=20, step=1)

In [0]:
stock.columns

Index(['Date', 'kospi', 'kosdaq', 'gold_fut_132030', 'Bond_273130'], dtype='object')

In [0]:
stock.values

array([['2020. 1. 2 오후 3:30:00', 2175.17, 674.02, 10845, 108215],
       ['2020. 1. 3 오후 3:30:00', 2176.46, 669.93, 11000, 108565],
       ['2020. 1. 6 오후 3:30:00', 2155.07, 655.31, 11245, 108745],
       ['2020. 1. 7 오후 3:30:00', 2175.54, 663.44, 11180, 108400],
       ['2020. 1. 8 오후 3:30:00', 2151.31, 640.94, 11360, 108270],
       ['2020. 1. 9 오후 3:30:00', 2186.45, 666.09, 11055, 107980],
       ['2020. 1. 10 오후 3:30:00', 2206.39, 673.03, 11035, 107760],
       ['2020. 1. 13 오후 3:30:00', 2229.26, 679.22, 11080, 107695],
       ['2020. 1. 14 오후 3:30:00', 2238.88, 678.71, 10975, 107860],
       ['2020. 1. 15 오후 3:30:00', 2230.98, 679.16, 11060, 108020],
       ['2020. 1. 16 오후 3:30:00', 2248.05, 686.52, 11060, 108015],
       ['2020. 1. 17 오후 3:30:00', 2250.57, 688.41, 11075, 107830],
       ['2020. 1. 20 오후 3:30:00', 2262.64, 683.47, 11140, 107775],
       ['2020. 1. 21 오후 3:30:00', 2239.69, 676.52, 11155, 108040],
       ['2020. 1. 22 오후 3:30:00', 2267.25, 688.25, 11050, 107995],
       ['2020. 1. 23 오후 3:30:00', 2246.13, 685.57, 11080, 107970],
       ['2020. 1. 28 오후 3:30:00', 2176.72, 664.7, 11250, 108450],
       ['2020. 1. 29 오후 3:30:00', 2185.28, 670.18, 11160, 108585],
       ['2020. 1. 30 오후 3:30:00', 2148.0, 656.39, 11225, 108810],
       ['2020. 1. 31 오후 3:30:00', 2119.01, 642.48, 11210, 108795]],
      dtype=object)

In [0]:
movie_2019.head(4)

   순위         영화명         개봉일  ...  대표국적  국적                 배급사
0   1        극한직업  2019-01-23  ...    한국  한국           씨제이이앤엠(주)
1   2  어벤져스: 엔드게임  2019-04-24  ...    미국  미국  월트디즈니컴퍼니코리아 유한책임회사
2   3      겨울왕국 2  2019-11-21  ...    미국  미국  월트디즈니컴퍼니코리아 유한책임회사
3   4         알라딘  2019-05-23  ...    미국  미국  월트디즈니컴퍼니코리아 유한책임회사

[4 rows x 11 columns]

In [0]:
movie_2019.index

RangeIndex(start=0, stop=30, step=1)

In [0]:
movie_2019.columns

Index(['순위', '영화명', '개봉일', '매출액', '매출액 점유율', '관객수', '스크린수', '상영횟수', '대표국적',
       '국적', '배급사'],
      dtype='object')

# 핵심 기능

## indexing/slicing

### **Series indexing/slicing**
* integer-location based: numpy indexing와 유사하게 동작함. 
* label-location based: 라벨로도 색인 가능!!

In [0]:
obj = pd.Series(np.arange(5), index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

#### **integer-location based**

In [0]:
obj[2]

2

In [0]:
obj[-1]

4

In [0]:
obj[[1,4]]

b    1
e    4
dtype: int64

In [0]:
obj[1:3]

b    1
c    2
dtype: int64

In [0]:
# boolean 
obj[obj<3]

a    0
b    1
c    2
dtype: int64

#### **label-location based**

In [0]:
obj['c']

2

In [0]:
obj.c

2

In [0]:
obj[['e','c']]

e    4
c    2
dtype: int64

**주의**: 라벨로 슬라이싱하면 시작점과 끝점을 포함!!!

In [0]:
obj['a':'c']

a    0
b    1
c    2
dtype: int64

In [0]:
obj['d':'e']=100

In [0]:
obj

a      0
b      1
c      2
d    100
e    100
dtype: int64

#### iloc, loc 
* Series.iloc: integer-location based
* Series.loc: label-location based

정수값을 담고 있는 축 색인이 있는 경우는?

In [0]:
obj2 = pd.Series(np.arange(3.))
obj2

0    0.0
1    1.0
2    2.0
dtype: float64

In [0]:
obj2[-1] # 실패

KeyError: ignored

정수 값을 가진 색인이 있으면 우선적으로 라벨 먼저 찾음

In [0]:
obj4 = pd.Series(np.arange(5)*10, index=[-1,0,1,2,3])
obj

a      0
b      1
c      2
d    100
e    100
dtype: int64

In [0]:
obj4[-1]

0

인덱스가 정수를 포함한 경우 사용자가 헷갈릴 수 있음.
=> loc, iloc을 사용하자. 

    - loc : label-based indexing
    - iloc : integer-location based indexing

In [0]:
obj3 = pd.Series(np.arange(0, 50, 10))
obj3

0     0
1    10
2    20
3    30
4    40
dtype: int64

In [0]:
obj3[:2]

0     0
1    10
dtype: int64

In [0]:
obj3.loc[:2]  #라벨은 시작점과 끝점을 포함

0     0
1    10
2    20
dtype: int64

In [0]:
obj3.iloc[:2]

0     0
1    10
dtype: int64

### **DataFrame indexing/slicing**

* DataFrame[컬럼명]
* DataFrame.컬럼명

* DataFrame[인덱스:인덱스]  **slicing할 때는 rows**

In [0]:
frame = pd.DataFrame(np.arange(15).reshape(3,5), 
                         columns = ['c1', 'c2', 'c3', 'c4', 'c5'],
                         index = ['r1', 'r2', 'r3'])
frame

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14

In [0]:
frame['c3']

r1     2
r2     7
r3    12
Name: c3, dtype: int64

In [0]:
frame.c3

r1     2
r2     7
r3    12
Name: c3, dtype: int64

In [0]:
frame[['c1', 'c4']]

    c1  c4
r1   0   3
r2   5   8
r3  10  13

In [0]:
frame['r1':'r2']

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9

**frame[컬럼명][인덱스]**

In [0]:
frame['c3']['r1']

2

In [0]:
frame['c3'][[0, 2]]

r1     2
r3    12
Name: c3, dtype: int64

#### iloc, loc 
* DataFrame.iloc: integer-location based
* DataFrame.loc: label-location based

In [0]:
frame.loc[['r1','r2'],['c2','c3','c4']]

    c2  c3  c4
r1   1   2   3
r2   6   7   8

In [0]:
frame.iloc[[0,1], 1:4]

    c2  c3  c4
r1   1   2   3
r2   6   7   8

In [0]:
stock.loc[::2, 'kospi']

0     2175.17
2     2155.07
4     2151.31
6     2206.39
8     2238.88
10    2248.05
12    2262.64
14    2267.25
16    2176.72
18    2148.00
Name: kospi, dtype: float64

In [0]:
stock.iloc[::2, 1]

0     2175.17
2     2155.07
4     2151.31
6     2206.39
8     2238.88
10    2248.05
12    2262.64
14    2267.25
16    2176.72
18    2148.00
Name: kospi, dtype: float64

## Quiz: Pandas_quiz_1.ipynb

## 산술연산

### Series
* index를 기준으로 연산 
* 짝이 맞지 않는 인덱스가 있는 경우 outer join과 유사하게 동작
* 짝이 맞지 않는 인덱스가 있는 경우, 없는 값을 기본값을 지정해주고 싶은 경우 메서드의 옵션 fill_value사용

In [0]:
s1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])

In [0]:
s2 = pd.Series([10, 20, 30, 40], index = ['a', 'b', 'c', 'd'])

In [0]:
s1+s2

a    11
b    22
c    33
d    44
dtype: int64

In [0]:
s1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])

In [0]:
s3 = pd.Series([2, 2, 2, 2], index = ['b', 'c', 'd', 'e'])

In [0]:
# a, e
s1+s3

a    NaN
b    4.0
c    5.0
d    6.0
e    NaN
dtype: float64

In [0]:
s1.add(s3, fill_value=0)

a    1.0
b    4.0
c    5.0
d    6.0
e    2.0
dtype: float64

### DataFrame
* index, column을 기준으로 연산 
* 짝이 맞지 않는 인덱스가 있는 경우 outer join과 유사하게 동작
* 짝이 맞지 않는 인덱스가 있는 경우, 없는 값을 기본값을 지정해주고 싶은 경우 메서드의 옵션 fill_value사용

|메서드|설명|
|---|---|
|add, radd|덧셈(+)을 위한 메서드|
|sub, rsub|뺄셈(-)을 위한 메서드|
|mul, rmul|곱셈(*)을 위한 메서드|
|div, rdiv|나눗셈(/)을 위한 메서드 |
|pow, rpow|멱승(**)을 위한 메서드 |
|floordiv, rfloordiv|소수점 내림(//)을 위한 메서드 |

In [0]:
d1 = pd.DataFrame(np.ones((3,2))*100, 
                  index=['r1', 'r2', 'r3'], columns =['c1', 'c2'])
d1

       c1     c2
r1  100.0  100.0
r2  100.0  100.0
r3  100.0  100.0

In [0]:
d2 = pd.DataFrame(np.ones((3,2))*200,
                  index=['r2', 'r3', 'r4'], columns =['c2', 'c3'])
d2

       c2     c3
r2  200.0  200.0
r3  200.0  200.0
r4  200.0  200.0

In [0]:
d1 + d2

    c1     c2  c3
r1 NaN    NaN NaN
r2 NaN  300.0 NaN
r3 NaN  300.0 NaN
r4 NaN    NaN NaN

In [0]:
# (r1, c3), (r4, c1)
d1.add(d2, fill_value=0)

       c1     c2     c3
r1  100.0  100.0    NaN
r2  100.0  300.0  200.0
r3  100.0  300.0  200.0
r4    NaN  200.0  200.0

### 기타

In [0]:
d3 = pd.DataFrame(np.arange(0,60,10).reshape(2,3), columns = list('abc'))
d3

    a   b   c
0   0  10  20
1  30  40  50

In [0]:
# dataframe + scalar
d3.div(10)

     a    b    c
0  0.0  1.0  2.0
1  3.0  4.0  5.0

In [0]:
d3.rdiv(10)

          a     b    c
0       inf  1.00  0.5
1  0.333333  0.25  0.2

DataFrame과 Series 간의 연산  
Series의 색인을 DataFrame의 컬럼에 맞추고 아래 로우로 전파함.

In [0]:
frame = pd.DataFrame(np.ones((3,3)), dtype=int, columns = list('abc'))
frame

   a  b  c
0  1  1  1
1  1  1  1
2  1  1  1

In [0]:
series = pd.Series([100, 200, 300], index = list('abc'))
series

a    100
b    200
c    300
dtype: int64

In [0]:
frame + series

     a    b    c
0  101  201  301
1  101  201  301
2  101  201  301

row에 대해 연산을 수행하고 싶다면 산술 연산 메서드를 사용  
- axis = 'index'  
- axis = 0

In [0]:
frame

   a  b  c
0  1  1  1
1  1  1  1
2  1  1  1

In [0]:
series3 =pd.Series([100, 200, 300])
series3

0    100
1    200
2    300
dtype: int64

In [0]:
frame.add(series3, axis=0)

     a    b    c
0  101  101  101
1  201  201  201
2  301  301  301

## 기술 통계 계산과 요약

### 요약 통계

|메서드|설명|
|---|---|
|describe|series나 dataframe의 각 컬럼에 대한 요약 통계|
|count| na 값을 제외한 값의 개수를 반환|
|min, max| 최소값, 최대값|
|argmin, argmax|최소값, 최대값을 가진 색인의 위치(정수)를 반환|
|idxmin, idxmax|최소값, 최대값을 가진 색인의 값을 반환|
|sum|합|
|mean, median|평균, 중앙값|
|var, std|분산, 표준편차|

* pandas 객체의 기술 통계는 누락된 데이터를 배제하고 처리함.

In [0]:
frame = pd.DataFrame([[10, 4, 'a'], [10, 2.5, 'b'], [np.nan, 10, 'a']], 
                     index=['i1', 'i2', 'i3'],
                      columns=['c1', 'c2', 'c3'])
frame

      c1    c2 c3
i1  10.0   4.0  a
i2  10.0   2.5  b
i3   NaN  10.0  a

In [0]:
frame.describe()

         c1         c2
count   2.0   3.000000
mean   10.0   5.500000
std     0.0   3.968627
min    10.0   2.500000
25%    10.0   3.250000
50%    10.0   4.000000
75%    10.0   7.000000
max    10.0  10.000000

In [0]:
frame.describe(include='object')

       c3
count   3
unique  2
top     a
freq    2

In [0]:
frame.max()

c1    10
c2    10
c3     b
dtype: object

In [0]:
frame.min(axis=1)

i1     4.0
i2     2.5
i3    10.0
dtype: float64

In [0]:
frame.sum()

c1      20
c2    16.5
c3     aba
dtype: object

### cov, corr

In [0]:
stock.head(3)

                    Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745

In [0]:
stock.cov()

                        kospi       kosdaq  gold_fut_132030    Bond_273130
kospi             1921.637020   571.318555     -2227.815789  -13197.083553
kosdaq             571.318555   197.144948     -1058.809474   -3720.835526
gold_fut_132030  -2227.815789 -1058.809474     13401.052632   20100.000000
Bond_273130     -13197.083553 -3720.835526     20100.000000  132999.671053

In [0]:
stock.corr()

                    kospi    kosdaq  gold_fut_132030  Bond_273130
kospi            1.000000  0.928218        -0.439010    -0.825500
kosdaq           0.928218  1.000000        -0.651412    -0.726645
gold_fut_132030 -0.439010 -0.651412         1.000000     0.476103
Bond_273130     -0.825500 -0.726645         0.476103     1.000000

In [0]:
stock['kospi'].corr(stock['Bond_273130'])

-0.8254998611070387

### unique, value_counts

|메서드|설명|
|---|---|
|unique|series에서 중복되는 값을 제외하고 유일값만 포함하는 배열을 반환.|
|value_conuts|series에서 유일값에 대한 색인과 도수를 계산|

In [0]:
obj = pd.Series([2, 1, 3, 3, 1, 5, np.nan, 1, 2])
obj

0    2.0
1    1.0
2    3.0
3    3.0
4    1.0
5    5.0
6    NaN
7    1.0
8    2.0
dtype: float64

In [0]:
obj.unique()

array([ 2.,  1.,  3.,  5., nan])

In [0]:
obj.value_counts()

1.0    3
3.0    2
2.0    2
5.0    1
dtype: int64

In [0]:
# normalize
obj.value_counts(normalize=True)

1.0    0.375
3.0    0.250
2.0    0.250
5.0    0.125
dtype: float64

In [0]:
obj = pd.Series(list('abcabcaaa')+[None])
obj

0       a
1       b
2       c
3       a
4       b
5       c
6       a
7       a
8       a
9    None
dtype: object

In [0]:
obj.unique()

array(['a', 'b', 'c', None], dtype=object)

In [0]:
obj.value_counts()

a    5
c    2
b    2
dtype: int64

In [0]:
data = pd.DataFrame({'c1': ['a', 'a', 'b', 'a'], 'c2':['b', None, 'b','b'], 'c3':['a', 'b', 'a', 'b']})
data

  c1    c2 c3
0  a     b  a
1  a  None  b
2  b     b  a
3  a     b  b

In [0]:
data.apply(pd.value_counts)  # unique(), value_counts() 는 series에만 적용 가능(dataframe 말고)

   c1   c2  c3
a   3  NaN   2
b   1  3.0   2

## 함수 적용과 매핑 apply, applymap, map


### Series
* **Series.map**: element 별로 함수 적용. 
*  **Series.apply**: element 별로 함수 적용. map 보다 더 복잡한 함수 사용 가능.

In [0]:
series = pd.Series(np.arange(1, 4, 1)*100)
series

0    100
1    200
2    300
dtype: int64

In [0]:
series.map('${}'.format)

0    $100
1    $200
2    $300
dtype: object

In [0]:
# lambda
f = lambda x: np.add(x, 3)

In [0]:
series.map(f)

0    103
1    203
2    303
dtype: int64

In [0]:
series.map({100:'C', 200:'B', 300:'A'})

0    C
1    B
2    A
dtype: object

In [0]:
s = pd.Series([20, 21, 12], index=['London', 'New York', 'Helsinki'])
s

London      20
New York    21
Helsinki    12
dtype: int64

In [0]:
def add_custom_values(x, **kwargs):
    for month in kwargs:
        x += kwargs[month]
    return x

In [0]:
s.apply(add_custom_values, june=30) #, july=20, august=25

London      50
New York    51
Helsinki    42
dtype: int64

### DataFrame 
* **DataFrame.applymap**: element 별로 함수 적용.
* **DataFrame.apply**: 축 별로 함수 적용.

In [0]:
frame = pd.DataFrame(np.arange(12).reshape(3, 4), dtype=int, columns = list('abcd'))
frame

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [0]:
f = lambda x: x.max()-x.min()
frame.apply(f)

a    8
b    8
c    8
d    8
dtype: int64

In [0]:
frame.apply(f, axis=1)

0    3
1    3
2    3
dtype: int64

In [0]:
f = lambda x: x**2
frame.applymap(f)

    a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

## 정렬

### Series 정렬

* Series.sort_index : index를 기준으로 정렬
* Series.sort_values: values를 기준으로 정렬

In [0]:
obj = pd.Series([1,2,3,-1,-2], index=list('adebc'))

In [0]:
obj

a    1
d    2
e    3
b   -1
c   -2
dtype: int64

In [0]:
obj.sort_index()

a    1
b   -1
c   -2
d    2
e    3
dtype: int64

내림차순 ascending=False

In [0]:
obj.sort_index(ascending=False)

e    3
d    2
c   -2
b   -1
a    1
dtype: int64

In [0]:
obj.sort_values()

c   -2
b   -1
a    1
d    2
e    3
dtype: int64

* 정렬할 때 비어 있는 값은 기본적으로 가장 마지막에 위치  
na_position = {‘first’, ‘last’} 옵션으로 조절

In [0]:
obj = pd.Series([10, np.nan, 20, 0, np.nan])

In [0]:
obj.sort_values()

3     0.0
0    10.0
2    20.0
1     NaN
4     NaN
dtype: float64

In [0]:
obj.sort_values(ascending=False)

2    20.0
0    10.0
3     0.0
1     NaN
4     NaN
dtype: float64

In [0]:
obj.sort_values(na_position='first')

1     NaN
4     NaN
3     0.0
0    10.0
2    20.0
dtype: float64

### DataFrame 정렬

* DataFrame.sort_index: index를 기준으로 정렬
* DataFrame.sort_values: values를 기준으로 정렬

In [0]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), index = list('acb'), columns = list('edf'))
frame

   e  d  f
a  0  1  2
c  3  4  5
b  6  7  8

In [0]:
frame.sort_index()

   e  d  f
a  0  1  2
b  6  7  8
c  3  4  5

In [0]:
frame.sort_index(axis=1)

   d  e  f
a  1  0  2
c  4  3  5
b  7  6  8

In [0]:
frame = pd.DataFrame({'a': [5, 4, 10, 10, 8], 'b': [2, 0, 3, 1, 4] })
frame

    a  b
0   5  2
1   4  0
2  10  3
3  10  1
4   8  4

In [0]:
frame.sort_values(by='a', ascending = False)

    a  b
2  10  3
3  10  1
4   8  4
0   5  2
1   4  0

In [0]:
frame.sort_values(by=['a', 'b'], ascending = [False, True])

    a  b
3  10  1
2  10  3
4   8  4
0   5  2
1   4  0

## Quiz: Pandas_quiz_2.ipynb

# 데이터 정제, 준비

## 데이터 삭제 drop
row, column 삭제하기

.drop()

In [0]:
frame = pd.DataFrame(np.arange(16).reshape(4,4), 
                         columns = ['c1', 'c2', 'c3', 'c4'],
                         index = ['r1', 'r2', 'r3','r4'])
frame

    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [0]:
frame.drop('r1')

    c1  c2  c3  c4
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [0]:
frame.drop('c2', axis = 1)

    c1  c3  c4
r1   0   2   3
r2   4   6   7
r3   8  10  11
r4  12  14  15

In [0]:
frame.drop(columns=['c3', 'c4'])

    c1  c2
r1   0   1
r2   4   5
r3   8   9
r4  12  13

In [0]:
# inplace
frame.drop(['r2'], inplace=True)
frame

    c1  c2  c3  c4
r1   0   1   2   3
r3   8   9  10  11
r4  12  13  14  15

In [0]:
# 할당 
frame = frame.drop(['r3'])
frame

    c1  c2  c3  c4
r1   0   1   2   3
r4  12  13  14  15

## 데이터 병합 concat, merge

### concat

In [0]:
s1 = pd.Series([100, 200], index=['c', 'b'])
s2 = pd.Series([300, 300, 300], index=['c', 'd', 'e'])
s3 = pd.Series([500, 600], index=['f', 'g'])

In [0]:
pd.concat([s1, s2, s3])

c    100
b    200
c    300
d    300
e    300
f    500
g    600
dtype: int64

In [0]:
# sort: 붙이는 축 반대 축을 정렬 할지 말지 결정 
pd.concat([s1, s3, s2], axis = 1, sort=False)

       0      1      2
c  100.0    NaN  300.0
b  200.0    NaN    NaN
f    NaN  500.0    NaN
g    NaN  600.0    NaN
d    NaN    NaN  300.0
e    NaN    NaN  300.0

In [0]:
data1 = pd.DataFrame({'id': ['01', '02', '03', '04', '05', '06'], 'col1': np.random.randint(0, 50, 6), 'col2':np.random.randint(1000, 2000, 6)})
data2 = pd.DataFrame({'id': ['04', '05', '06', '07'], 'col1': np.random.randint(1000, 5000, 4)})

In [0]:
pd.concat([data1, data2], sort=False)

   id  col1    col2
0  01     1  1415.0
1  02    34  1020.0
2  03    32  1613.0
3  04    27  1705.0
4  05    15  1610.0
5  06    25  1797.0
0  04  4434     NaN
1  05  1639     NaN
2  06  4995     NaN
3  07  4190     NaN

In [0]:
pd.concat([data1, data2], axis =1)

   id  col1  col2   id    col1
0  01     1  1415   04  4434.0
1  02    34  1020   05  1639.0
2  03    32  1613   06  4995.0
3  04    27  1705   07  4190.0
4  05    15  1610  NaN     NaN
5  06    25  1797  NaN     NaN

### merge

keys를 이용해 데이터의 row를 연결시켜 합침.
(sql의 join과 유사)

* 인자
    - how: {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’

In [0]:
data1 = pd.DataFrame({'id': ['01', '02', '03', '04', '05', '06'], 'col1': np.random.randint(0, 50, 6), 'col2':np.random.randint(1000, 2000, 6)})
data1

   id  col1  col2
0  01    32  1391
1  02    43  1412
2  03    29  1238
3  04     2  1279
4  05    21  1466
5  06     0  1100

In [0]:
data2 = pd.DataFrame({'id': ['04', '05', '06', '07'], 'col1': np.random.randint(1000, 5000, 4)})
data2

   id  col1
0  04  3258
1  05  2975
2  06  2015
3  07  4415

In [0]:
#inner join
pd.merge(data1, data2, on='id')

   id  col1_x  col2  col1_y
0  04       2  1279    3258
1  05      21  1466    2975
2  06       0  1100    2015

In [0]:
#left join
pd.merge(data1, data2, on='id', how='left')

   id  col1_x  col2  col1_y
0  01      32  1391     NaN
1  02      43  1412     NaN
2  03      29  1238     NaN
3  04       2  1279  3258.0
4  05      21  1466  2975.0
5  06       0  1100  2015.0

In [0]:
# outer join
pd.merge(data1, data2, on='id', how='outer')

   id  col1_x    col2  col1_y
0  01    32.0  1391.0     NaN
1  02    43.0  1412.0     NaN
2  03    29.0  1238.0     NaN
3  04     2.0  1279.0  3258.0
4  05    21.0  1466.0  2975.0
5  06     0.0  1100.0  2015.0
6  07     NaN     NaN  4415.0

In [0]:
# key 다를 경우
data1 = pd.DataFrame({'lkey': ['a', 'b', 'c', 'd'], 'value': [1, 2, 3, 5]})
data2 = pd.DataFrame({'rkey': ['d', 'e', 'a', 'c'], 'value': [5, 6, 7, 8]})

pd.merge(data1, data2, left_on='lkey', right_on='rkey')

  lkey  value_x rkey  value_y
0    a        1    a        7
1    c        3    c        8
2    d        5    d        5

## missing data 처리

|인자|설명|
|---|---|
|isnull|누락되거나 NA(not available) 값을 알려주는 불리언 값들이 저장된 객체를 반환|
|notnull|isnull과 반대되는 메서드|
|fillna|누락된 데이터에 값을 채우는 메서드. (특정한 값이나 ffill, bfill 같은 보간 메서드 적용)|
|dropna|누락된 데이터가 있는 축(로우, 컬럼)을 제외시키는 메서드|

In [0]:
obj = pd.Series(['apple', 'mango', np.nan, None, 'peach'])

In [0]:
obj.isnull()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [0]:
obj.notnull()

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [0]:
obj.dropna()

0    apple
1    mango
4    peach
dtype: object

In [0]:
obj.fillna('-')

0    apple
1    mango
2        -
3        -
4    peach
dtype: object

In [0]:
frame = pd.DataFrame([[np.nan, np.nan, np.nan, np.nan], [10, 5, 40, 6],
                      [5, 2, 30, 8], [20, np.nan, 20, 6], [15, 3, 10, np.nan]],
                     columns=['x1', 'x2', 'x3', 'y'])
frame

     x1   x2    x3    y
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [0]:
frame.dropna()

     x1   x2    x3    y
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0

In [0]:
# how
frame.dropna(how='all')

     x1   x2    x3    y
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [0]:
frame.dropna(subset=['y'])

     x1   x2    x3    y
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0

In [0]:
frame['e'] = np.nan
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [0]:
# axis 
frame.dropna(axis=1, how='all')

     x1   x2    x3    y
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [0]:
frame.fillna(0)

     x1   x2    x3    y    e
0   0.0  0.0   0.0  0.0  0.0
1  10.0  5.0  40.0  6.0  0.0
2   5.0  2.0  30.0  8.0  0.0
3  20.0  0.0  20.0  6.0  0.0
4  15.0  3.0  10.0  0.0  0.0

In [0]:
frame.fillna({'x1': 10, 'y':0})

     x1   x2    x3    y   e
0  10.0  NaN   NaN  0.0 NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  0.0 NaN

In [0]:
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [0]:
# (4, y)
frame.fillna(method='bfill')

     x1   x2    x3    y   e
0  10.0  5.0  40.0  6.0 NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  3.0  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [0]:
# row1
frame.fillna(method='ffill')

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  2.0  20.0  6.0 NaN
4  15.0  3.0  10.0  6.0 NaN

In [0]:
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

## 데이터 변형

### 중복제거

    - .duplicated() : 각 로우가 중복인지(True) 아닌지(False) 알려주는 불리언 series 반환 
    - .drop_duplicates(): duplicated 배열이 False인 dataframe 반환

In [0]:
data = pd.DataFrame({'id':['0001', '0002', '0003', '0001'], 'name': ['a', 'b', 'c', 'a']})
data

     id name
0  0001    a
1  0002    b
2  0003    c
3  0001    a

In [0]:
data.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [0]:
data.drop_duplicates()

     id name
0  0001    a
1  0002    b
2  0003    c

In [0]:
data['phone'] = range(4)
data

     id name  phone
0  0001    a      0
1  0002    b      1
2  0003    c      2
3  0001    a      3

In [0]:
data.drop_duplicates(subset=['id'], keep='last')

     id name  phone
1  0002    b      1
2  0003    c      2
3  0001    a      3

### 값 치환하기

.replace

In [0]:
obj = pd.Series([10, -999, 4, 5, 7, 'n'])

In [0]:
obj.replace(-999, np.nan)

0     10
1    NaN
2      4
3      5
4      7
5      n
dtype: object

In [0]:
obj.replace([-999, 'n'], np.nan)

0    10.0
1     NaN
2     4.0
3     5.0
4     7.0
5     NaN
dtype: float64

### binning

In [0]:
ages = [20, 35, 67, 39, 59, 44, 56, 77, 28, 20, 22, 80, 32, 46, 52, 19, 33, 5, 15, 50, 29, 21, 33, 48, 85, 80, 31, 10]

In [0]:
bins = [0, 20, 40, 60, 100]

In [0]:
cuts = pd.cut(ages, bins)
cuts

[(0, 20], (20, 40], (60, 100], (20, 40], (40, 60], ..., (40, 60], (60, 100], (60, 100], (20, 40], (0, 20]]
Length: 28
Categories (4, interval[int64]): [(0, 20] < (20, 40] < (40, 60] < (60, 100]]

In [0]:
cuts.categories

IntervalIndex([(0, 20], (20, 40], (40, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [0]:
cuts.codes

array([0, 1, 3, 1, 2, 2, 2, 3, 1, 0, 1, 3, 1, 2, 2, 0, 1, 0, 0, 2, 1, 1,
       1, 2, 3, 3, 1, 0], dtype=int8)

In [0]:
cuts.value_counts()

(0, 20]       6
(20, 40]     10
(40, 60]      7
(60, 100]     5
dtype: int64

In [0]:
group_names = ['10대 이하','20-30대','40-50대','60대 이상']
pd.cut(ages, bins, labels=group_names)

[10대 이하, 20-30대, 60대 이상, 20-30대, 40-50대, ..., 40-50대, 60대 이상, 60대 이상, 20-30대, 10대 이하]
Length: 28
Categories (4, object): [10대 이하 < 20-30대 < 40-50대 < 60대 이상]

In [0]:
# 구간을 균등한 길이로 나눔
pd.cut(ages, 4, precision=1).value_counts()

(4.9, 25.0]     8
(25.0, 45.0]    9
(45.0, 65.0]    6
(65.0, 85.0]    5
dtype: int64

In [0]:
# 개수들이 균등한 비율이 되도록 나눔
pd.qcut(ages, 4).value_counts()

(4.999, 21.75]    7
(21.75, 34.0]     7
(34.0, 53.0]      7
(53.0, 85.0]      7
dtype: int64

### get_dummies
명목형 변수의 경우을 one-hot encoding을 해주는 경우가 있음.

In [0]:
df = pd.DataFrame({'col1': [10, 20, 30],
                   'col2': ['a', 'b', 'a']})
df

   col1 col2
0    10    a
1    20    b
2    30    a

In [0]:
pd.get_dummies(df)

   col1  col2_a  col2_b
0    10       1       0
1    20       0       1
2    30       1       0

In [0]:
df = pd.DataFrame({'col1': ['001', '002', '003', '004', '005', '006'], 
                   'col2': [10, 20, 30, 40, 50, 60],
                   'col3': ['서울시', '경기도', '서울시', '제주도', '경기도', '서울시']})
df

  col1  col2 col3
0  001    10  서울시
1  002    20  경기도
2  003    30  서울시
3  004    40  제주도
4  005    50  경기도
5  006    60  서울시

In [0]:
pd.get_dummies(df)

   col2  col1_001  col1_002  col1_003  ...  col1_006  col3_경기도  col3_서울시  col3_제주도
0    10         1         0         0  ...         0         0         1         0
1    20         0         1         0  ...         0         1         0         0
2    30         0         0         1  ...         0         0         1         0
3    40         0         0         0  ...         0         0         0         1
4    50         0         0         0  ...         0         1         0         0
5    60         0         0         0  ...         1         0         1         0

[6 rows x 10 columns]

In [0]:
pd.get_dummies(df, columns=['col3'])

  col1  col2  col3_경기도  col3_서울시  col3_제주도
0  001    10         0         1         0
1  002    20         1         0         0
2  003    30         0         1         0
3  004    40         0         0         1
4  005    50         1         0         0
5  006    60         0         1         0

In [0]:
pd.get_dummies(df, columns=['col3'], prefix=['state'])

  col1  col2  state_경기도  state_서울시  state_제주도
0  001    10          0          1          0
1  002    20          1          0          0
2  003    30          0          1          0
3  004    40          0          0          1
4  005    50          1          0          0
5  006    60          0          1          0

In [0]:
movie_2019.head(2)

   순위         영화명         개봉일  ...  대표국적  국적                 배급사
0   1        극한직업  2019-01-23  ...    한국  한국           씨제이이앤엠(주)
1   2  어벤져스: 엔드게임  2019-04-24  ...    미국  미국  월트디즈니컴퍼니코리아 유한책임회사

[2 rows x 11 columns]

## groupby

### groupby

In [0]:
kbo = pd.read_csv('kbo.csv')
kbo.head()

     연도  순위   팀  경기수   승   패  무     승률   게임차
0  2019   1  두산  144  88  55  1  0.615   0.0
1  2019   2  키움  144  86  57  1  0.601   2.0
2  2019   3  SK  144  88  55  1  0.615   0.0
3  2019   4  LG  144  79  64  1  0.552   9.0
4  2019   5  NC  144  73  69  2  0.514  14.5

In [0]:
kbo['연도'].unique()

array([2019, 2018, 2017])

In [0]:
kbo['팀'].unique()

array(['두산', '키움', 'SK', 'LG', 'NC', 'KT', 'KIA', '삼성', '한화', '롯데', '넥센'],
      dtype=object)

In [0]:
kbo.groupby('팀').count()

     연도  순위  경기수  승  패  무  승률  게임차
팀
KIA   3   3    3  3  3  3   3    3
KT    3   3    3  3  3  3   3    3
LG    3   3    3  3  3  3   3    3
NC    3   3    3  3  3  3   3    3
SK    3   3    3  3  3  3   3    3
넥센    2   2    2  2  2  2   2    2
두산    3   3    3  3  3  3   3    3
롯데    3   3    3  3  3  3   3    3
삼성    3   3    3  3  3  3   3    3
키움    1   1    1  1  1  1   1    1
한화    3   3    3  3  3  3   3    3

In [0]:
kbo.groupby('팀').mean()

         연도        순위    경기수  ...         무        승률        게임차
팀                             ...
KIA  2018.0  4.333333  144.0  ...  1.000000  0.510333  11.333333
KT   2018.0  8.333333  144.0  ...  1.666667  0.421667  24.000000
LG   2018.0  6.000000  144.0  ...  1.666667  0.505667  12.000000
NC   2018.0  6.333333  144.0  ...  2.000000  0.493333  13.833333
SK   2018.0  3.333333  144.0  ...  1.000000  0.561333   4.000000
넥센   2017.5  5.500000  144.0  ...  1.000000  0.503500  10.500000
두산   2018.0  1.333333  144.0  ...  1.333333  0.619000  -4.166667
롯데   2018.0  6.666667  144.0  ...  2.333333  0.460667  18.333333
삼성   2018.0  7.333333  144.0  ...  3.333333  0.434000  22.166667
키움   2019.0  2.000000  144.0  ...  1.000000  0.601000   2.000000
한화   2018.0  6.666667  144.0  ...  0.666667  0.456000  19.166667

[11 rows x 8 columns]

In [0]:
kbo.groupby('팀')['승률'].max()

팀
KIA    0.608
KT     0.500
LG     0.552
NC     0.560
SK     0.615
넥센     0.521
두산     0.646
롯데     0.563
삼성     0.486
키움     0.601
한화     0.535
Name: 승률, dtype: float64

In [0]:
kbo.groupby(['연도','팀'])['승률'].sum()

연도    팀
2017  KIA    0.608
      KT     0.347
      LG     0.489
      NC     0.560
      SK     0.524
      넥센     0.486
      두산     0.596
      롯데     0.563
      삼성     0.396
      한화     0.430
2018  KIA    0.486
      KT     0.418
      LG     0.476
      NC     0.406
      SK     0.545
      넥센     0.521
      두산     0.646
      롯데     0.479
      삼성     0.486
      한화     0.535
2019  KIA    0.437
      KT     0.500
      LG     0.552
      NC     0.514
      SK     0.615
      두산     0.615
      롯데     0.340
      삼성     0.420
      키움     0.601
      한화     0.403
Name: 승률, dtype: float64

### Hierarchical Indexing
multiple (two or more) index levels on an axis

In [0]:
kbo_h = kbo.groupby(['연도','팀'])['승률'].mean()
kbo_h.index

MultiIndex([(2017, 'KIA'),
            (2017,  'KT'),
            (2017,  'LG'),
            (2017,  'NC'),
            (2017,  'SK'),
            (2017,  '넥센'),
            (2017,  '두산'),
            (2017,  '롯데'),
            (2017,  '삼성'),
            (2017,  '한화'),
            (2018, 'KIA'),
            (2018,  'KT'),
            (2018,  'LG'),
            (2018,  'NC'),
            (2018,  'SK'),
            (2018,  '넥센'),
            (2018,  '두산'),
            (2018,  '롯데'),
            (2018,  '삼성'),
            (2018,  '한화'),
            (2019, 'KIA'),
            (2019,  'KT'),
            (2019,  'LG'),
            (2019,  'NC'),
            (2019,  'SK'),
            (2019,  '두산'),
            (2019,  '롯데'),
            (2019,  '삼성'),
            (2019,  '키움'),
            (2019,  '한화')],
           names=['연도', '팀'])

* Index level을 기준으로 기본 연산 수행 가능

In [0]:
kbo_h.sum(level=0)

연도
2017    4.999
2018    4.998
2019    4.997
Name: 승률, dtype: float64

In [0]:
kbo_h.mean(level=1).sort_values(ascending=False)

팀
두산     0.619000
키움     0.601000
SK     0.561333
KIA    0.510333
LG     0.505667
넥센     0.503500
NC     0.493333
롯데     0.460667
한화     0.456000
삼성     0.434000
KT     0.421667
Name: 승률, dtype: float64

* swaplevel: index level 변경

In [0]:
kbo_h.swaplevel()

팀    연도
KIA  2017    0.608
KT   2017    0.347
LG   2017    0.489
NC   2017    0.560
SK   2017    0.524
넥센   2017    0.486
두산   2017    0.596
롯데   2017    0.563
삼성   2017    0.396
한화   2017    0.430
KIA  2018    0.486
KT   2018    0.418
LG   2018    0.476
NC   2018    0.406
SK   2018    0.545
넥센   2018    0.521
두산   2018    0.646
롯데   2018    0.479
삼성   2018    0.486
한화   2018    0.535
KIA  2019    0.437
KT   2019    0.500
LG   2019    0.552
NC   2019    0.514
SK   2019    0.615
두산   2019    0.615
롯데   2019    0.340
삼성   2019    0.420
키움   2019    0.601
한화   2019    0.403
Name: 승률, dtype: float64

* unstack: group으로 묶여진 데이터를 matrix 형태로 전환

In [0]:
kbo_h.unstack()

팀       KIA     KT     LG     NC     SK  ...     두산     롯데     삼성     키움     한화
연도                                       ...
2017  0.608  0.347  0.489  0.560  0.524  ...  0.596  0.563  0.396    NaN  0.430
2018  0.486  0.418  0.476  0.406  0.545  ...  0.646  0.479  0.486    NaN  0.535
2019  0.437  0.500  0.552  0.514  0.615  ...  0.615  0.340  0.420  0.601  0.403

[3 rows x 11 columns]

### .groupby.get_group
    - 특정한 key값을 가진 그룹의 정보만 추출

In [0]:
grouped= kbo.groupby('팀')
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [0]:
for n, g in grouped:
    print(n)
    print(g)
    print('-'*50)

KIA
      연도  순위    팀  경기수   승   패  무     승률   게임차
6   2019   7  KIA  144  62  80  2  0.437  25.5
14  2018   5  KIA  144  70  74  0  0.486   8.5
20  2017   1  KIA  144  87  56  1  0.608   0.0
--------------------------------------------------
KT
      연도  순위   팀  경기수   승   패  무     승률   게임차
5   2019   6  KT  144  71  71  2  0.500  16.5
18  2018   9  KT  144  59  82  3  0.418  18.0
29  2017  10  KT  144  50  94  0  0.347  37.5
--------------------------------------------------
LG
      연도  순위   팀  경기수   승   패  무     승률   게임차
3   2019   4  LG  144  79  64  1  0.552   9.0
17  2018   8  LG  144  68  75  1  0.476  10.0
25  2017   6  LG  144  69  72  3  0.489  17.0
--------------------------------------------------
NC
      연도  순위   팀  경기수   승   패  무     승률   게임차
4   2019   5  NC  144  73  69  2  0.514  14.5
19  2018  10  NC  144  58  85  1  0.406  20.0
23  2017   4  NC  144  79  62  3  0.560   7.0
--------------------------------------------------
SK
      연도  순위   팀  경기수   승   패  무     승률   게임차
2   2019   3  SK  144  88  55  1  0.615   0.0
11  2018   2  SK  144  78  65  1  0.545   0.0
24  2017   5  SK  144  75  68  1  0.524  12.0
--------------------------------------------------
넥센
      연도  순위   팀  경기수   승   패  무     승률   게임차
13  2018   4  넥센  144  75  69  0  0.521   3.5
26  2017   7  넥센  144  69  73  2  0.486  17.5
--------------------------------------------------
두산
      연도  순위   팀  경기수   승   패  무     승률   게임차
0   2019   1  두산  144  88  55  1  0.615   0.0
10  2018   1  두산  144  93  51  0  0.646 -14.5
21  2017   2  두산  144  84  57  3  0.596   2.0
--------------------------------------------------
롯데
      연도  순위   팀  경기수   승   패  무     승률   게임차
9   2019  10  롯데  144  48  93  3  0.340  39.0
16  2018   7  롯데  144  68  74  2  0.479   9.5
22  2017   3  롯데  144  80  62  2  0.563   6.5
--------------------------------------------------
삼성
      연도  순위   팀  경기수   승   패  무     승률   게임차
7   2019   8  삼성  144  60  83  1  0.420  28.0
15  2018   5  삼성  144  68  72  4  0.486   8.5
28  2017   9  삼성  144  55  84  5  0.396  30.0
--------------------------------------------------
키움
     연도  순위   팀  경기수   승   패  무     승률  게임차
1  2019   2  키움  144  86  57  1  0.601  2.0
--------------------------------------------------
한화
      연도  순위   팀  경기수   승   패  무     승률   게임차
8   2019   9  한화  144  58  86  0  0.403  30.5
12  2018   3  한화  144  77  67  0  0.535   1.5
27  2017   8  한화  144  61  81  2  0.430  25.5
--------------------------------------------------

In [0]:
grouped.get_group('한화')

      연도  순위   팀  경기수   승   패  무     승률   게임차
8   2019   9  한화  144  58  86  0  0.403  30.5
12  2018   3  한화  144  77  67  0  0.535   1.5
27  2017   8  한화  144  61  81  2  0.430  25.5

### groupby.agg
- 그룹별로 특정한 집계 함수 적용

In [0]:
grouped.agg([np.mean, np.std])

         연도                  순위  ...        승률        게임차
       mean       std      mean  ...       std       mean        std
팀                                ...
KIA  2018.0  1.000000  4.333333  ...  0.088059  11.333333  12.983964
KT   2018.0  1.000000  8.333333  ...  0.076566  24.000000  11.715375
LG   2018.0  1.000000  6.000000  ...  0.040649  12.000000   4.358899
NC   2018.0  1.000000  6.333333  ...  0.079053  13.833333   6.525591
SK   2018.0  1.000000  3.333333  ...  0.047648   4.000000   6.928203
넥센   2017.5  0.707107  5.500000  ...  0.024749  10.500000   9.899495
두산   2018.0  1.000000  1.333333  ...  0.025239  -4.166667   9.004628
롯데   2018.0  1.000000  6.666667  ...  0.112625  18.333333  17.960605
삼성   2018.0  1.000000  7.333333  ...  0.046605  22.166667  11.877851
키움   2019.0       NaN  2.000000  ...       NaN   2.000000        NaN
한화   2018.0  1.000000  6.666667  ...  0.069735  19.166667  15.502688

[11 rows x 16 columns]

In [0]:
grouped.agg({'순위':np.mean, '승률':[np.mean, np.std]})

           순위        승률
         mean      mean       std
팀
KIA  4.333333  0.510333  0.088059
KT   8.333333  0.421667  0.076566
LG   6.000000  0.505667  0.040649
NC   6.333333  0.493333  0.079053
SK   3.333333  0.561333  0.047648
넥센   5.500000  0.503500  0.024749
두산   1.333333  0.619000  0.025239
롯데   6.666667  0.460667  0.112625
삼성   7.333333  0.434000  0.046605
키움   2.000000  0.601000       NaN
한화   6.666667  0.456000  0.069735

### groupby.filter

In [0]:
kbo.groupby('팀').filter(lambda x: len(x)==2)

      연도  순위   팀  경기수   승   패  무     승률   게임차
13  2018   4  넥센  144  75  69  0  0.521   3.5
26  2017   7  넥센  144  69  73  2  0.486  17.5

In [0]:
kbo.groupby('팀').filter(lambda x: x['순위'].min()==1)

      연도  순위    팀  경기수   승   패  무     승률   게임차
0   2019   1   두산  144  88  55  1  0.615   0.0
6   2019   7  KIA  144  62  80  2  0.437  25.5
10  2018   1   두산  144  93  51  0  0.646 -14.5
14  2018   5  KIA  144  70  74  0  0.486   8.5
20  2017   1  KIA  144  87  56  1  0.608   0.0
21  2017   2   두산  144  84  57  3  0.596   2.0

In [0]:
kbo.groupby('팀').filter(lambda x: x['순위'].min()==1)

In [0]:
df = pd.DataFrame({'col1': [0, 1, 2],
                   'col2': [10, 20, 30],
                   'col3': ['a', 'b', 'c']}, dtype='object')

In [0]:
df

  col1 col2 col3
0    0   10    a
1    1   20    b
2    2   30    c

In [0]:
df['col2','col3']

KeyError: ignored

In [0]:
obj = pd.Series([10, 20, 30, 40], index=['a','b','c', 'd'])

In [0]:
obj

a    10
b    20
c    30
d    40
dtype: int64

In [0]:
obj[1:3]

b    20
c    30
dtype: int64

In [0]:
obj = pd.Series([10, 20, 30, 40], index=['a','b','c', 'd'])

In [0]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),

                         columns = ['c1', 'c2', 'c3'],

                         index = ['r1', 'r2', 'r3'])

In [0]:
frame

    c1  c2  c3
r1   0   1   2
r2   3   4   5
r3   6   7   8

In [0]:
frame['r1':'r2']

    c1  c2  c3
r1   0   1   2
r2   3   4   5

In [0]:
frame.loc[['r1','r2'],:]

    c1  c2  c3
r1   0   1   2
r2   3   4   5

In [0]:
frame.loc[:,['c1','c2']]

    c1  c2
r1   0   1
r2   3   4
r3   6   7