In [0]:
import numpy as np
import pandas as pd

In [0]:
frame = pd.DataFrame(np.arange(10, 22, 1).reshape(4, 3), 

                         columns = ['c1', 'c2', 'c3'],

                         index = ['r1', 'r2', 'r3','r4'])

In [17]:
frame.drop(columns='c2')

    c1  c3
r1  10  12
r2  13  15
r3  16  18
r4  19  21

In [0]:
s1 = pd.Series(['A', 'C'])
s2 = pd.Series(['D', 'B'])

In [20]:
pd.concat([s1,s2],axis=1)

   0  1
0  A  D
1  C  B

In [21]:
pd.add([s1,s2])

AttributeError: ignored

In [0]:
df1 = pd.DataFrame({'key': ['a1', 'a2', 'a3', 'a4'],

                    'value': [1, 2, 3, 4]})

df2 = pd.DataFrame({'key': ['a1', 'a2', 'a3', 'a5'],

                    'value': [5, 6, 7, 8]})

In [24]:
df1

  key  value
0  a1      1
1  a2      2
2  a3      3
3  a4      4

In [25]:
df2

  key  value
0  a1      5
1  a2      6
2  a3      7
3  a5      8

In [26]:
pd.merge(df1,df2, how='left', on='key')

  key  value_x  value_y
0  a1        1      5.0
1  a2        2      6.0
2  a3        3      7.0
3  a4        4      NaN

In [5]:
s = pd.Series(['a1', 'b2', 'a2', 'd2'])

s.apply(lambda x: x[0])

0    a
1    b
2    a
3    d
dtype: object

In [7]:
frame = pd.DataFrame([[10, 3, 5, 0], [-1, 20, 4, 5]])

frame.applymap(lambda x: str(x)+'점')

     0    1   2   3
0  10점   3점  5점  0점
1  -1점  20점  4점  5점

In [11]:
frame = pd.DataFrame([[10, 3, 5, 0],
                      [-1, 20, 4, 5]])
frame.applymap(lambda x:max(x))

TypeError: ignored

In [0]:
'''
#colab사용시 
from google.colab import drive
drive.mount('/content/drive')
'''

In [0]:
'''
import os
from pathlib import Path
data_folder = "_share/_2020_04/data"

base_path = Path("/content/drive/My Drive/")
data_path = base_path / data_folder 
os.chdir(data_path)

print(f"현재 디렉토리 위치: {os.getcwd()}")
'''

# 1. 
주어진 리스트를 newspaper 라는 변수명의 Series 객체로 만들기

In [0]:
s =['경향신문신문', '국민일보신문', '동아일보신문', '문화일보신문', '서울신문신문', 
    '세계일보신문', '조선일보신문', '중앙일보신문', '한겨레신문', '한국일보신문']

In [0]:
'''
output:
0    경향신문신문
1    국민일보신문
2    동아일보신문
3    문화일보신문
4    서울신문신문
5    세계일보신문
6    조선일보신문
7    중앙일보신문
8     한겨레신문
9    한국일보신문
dtype: object
'''

# 2.
주어진 리스트를 기반으로 sales라는 변수명의 Series 객체를 만들어 볼 것.  
index를 위에서 정의한 newspaper로 한다.

In [0]:
np.random.seed(1004)
n = np.random.randint(100, 999, 10)*100
n

In [0]:
'''
output:
경향신문신문    10200
국민일보신문    62300
동아일보신문    13100
문화일보신문    42500
서울신문신문    33900
세계일보신문    29900
조선일보신문    11400
중앙일보신문    96300
한겨레신문     79200
한국일보신문    59700
dtype: int64
'''

# 3.
Series 데이터인 sales를 통해 '한겨레신문', '조선일보신문'의 판매량을 함께 반환할 것.

In [0]:
'''
output:
한겨레신문     79200
조선일보신문    11400
dtype: int64
'''

# 4. 
변수 sales를 통해 값이 50000 이상인 신문사만 추출하기

In [0]:
'''
국민일보신문    62300
중앙일보신문    96300
한겨레신문     79200
한국일보신문    59700
dtype: int64
'''

값이 20000 이하인 신문사에 10000 만큼 더해주기

In [0]:
'''
변경전:
경향신문신문    10200
국민일보신문    62300
동아일보신문    13100
문화일보신문    42500
서울신문신문    33900
세계일보신문    29900
한겨레신문     79200
한국일보신문    59700
dtype: int64
----------------------
변경후:
경향신문신문    30200
국민일보신문    62300
동아일보신문    33100
문화일보신문    42500
서울신문신문    33900
세계일보신문    29900
한겨레신문     79200
한국일보신문    59700
dtype: int64
'''

# 5.
파일명이 quiz_1_stock.csv인 데이터를 읽어와 stock 이라는 변수명으로 저장하기

In [0]:
'''
output:
 	날짜 	체결가 	전일비 	등락률 	거래량(천주) 	거래대금(백만)
0 	2020.02.07 	2211.95 	하락 15.99 	-1% 	800342 	8813174
1 	2020.02.06 	2227.94 	상승 62.31 	3% 	695216 	8334737
2 	2020.02.05 	2165.63 	상승 7.73 	0% 	574395 	7736275
3 	2020.02.04 	2157.90 	상승 39.02 	2% 	624641 	7791178
...
과 같은 데이터 프레임
'''

# 6.
stock의 '날짜', '등략률' 두 컬럼만 갖는 데이터 프레임을 추출하기

In [0]:
'''
output:
 	날짜 	등락률
0 	2020.02.07 	-1%
1 	2020.02.06 	3%
2 	2020.02.05 	0%
3 	2020.02.04 	2%
4 	2020.02.03 	0%
...
과 같은 데이터 프레임

'''

# 7.
stock 데이터를 통해 row index가 0부터 5까지이고, column명이 '날짜', '거래량(천주)', '체결가' 인 데이터를 추출해보자  
2가지 방법으로 해보기  
* iloc
* loc

In [0]:
'''
output:
 	날짜 	거래량(천주) 	체결가
0 	2020.02.07 	800342 	2211.95
1 	2020.02.06 	695216 	2227.94
2 	2020.02.05 	574395 	2165.63
3 	2020.02.04 	624641 	2157.90
4 	2020.02.03 	836699 	2118.88
'''
# iloc 사용 - tip: 날짜, 거래량(천주), 체결가의 integer index를 먼저 확인해보자

In [0]:
# loc 사용

# 8.
stock 데이터를 통해 거래대금(백만)이 8000000이 넘는 row만 추출해보기

In [0]:
'''
output:
 	날짜 	체결가 	전일비 	등락률 	거래량(천주) 	거래대금(백만)
0 	2020.02.07 	2211.95 	하락 15.99 	-1% 	800342 	8813174
1 	2020.02.06 	2227.94 	상승 62.31 	3% 	695216 	8334737
4 	2020.02.03 	2118.88 	하락 0.13 	0% 	836699 	8068704
8 	2020.01.28 	2176.72 	하락 69.41 	-3% 	808878 	8818232
'''

# 9.
체결가가 2210 이하이고, 거래량(천주)도 700000 이하인 날짜만 추출

In [0]:
'''
2    2020.02.05 
3    2020.02.04 
6    2020.01.30 
7    2020.01.29 
Name: 날짜, dtype: object
'''